@startuml
node "Рабочее устройство" {
    [Пользовательский интерфейс]
}

node "Сервер склада" {
    [Информационная система склада]
}

node "Сервер базы данных" {
    [База данных]
}

[Пользовательский интерфейс] --> [Информационная система склада]: HTTP
[Информационная система склада] --> [База данных]: SQL
@enduml
